spring.jpa.properties.hibernate.hbm2ddl.import_files: author.sql, type.sql
spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true

spring.rabbitmq.dynamic: false
spring.jpa.properties.hibernate.show_sql: true
